[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "functions"

# This is the new, correct way to set a global timeout
[functions."*"]
  timeout = 25

[dev]
  framework = "vite"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-functions-install-core"