[build]
  publish = "dist"
  command = "npm run build"

# This is the single, correct [functions] block
[functions]
  directory = "functions"
  timeout = 25

[dev]
  framework = "vite"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-functions-install-core"