[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "functions"

[dev]
  framework = "vite"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[plugins]]
package = "@netlify/plugin-functions-install-core"